{% set name = "linear_operator" %}
{% set version = "0.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9e2663879f1a2b28631bf7ef34892c4e5749893e711c8ef0ab0a39aff70a654

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python >={{ python_min }}
    - jaxtyping
    - pytorch >=2.0
    - scipy
    - mpmath >=0.19,<=1.3

test:
  imports:
    - linear_operator
    - linear_operator.functions
    - linear_operator.operators
    - linear_operator.test
    - linear_operator.utils
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -c "import linear_operator; print(linear_operator.__version__)"

about:
  home: https://github.com/cornellius-gp/linear_operator
  summary: A LinearOperator implementation to wrap the numerical nuts and bolts of GPyTorch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/cornellius-gp/linear_operator

extra:
  recipe-maintainers:
    - AdrianSosic
    - ngam
    - thewchan
