{% set name = "linear_operator" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64d5fabd81bc77b3c84af966087bd2fae07b41a7c3823f28cfab49f3066fed1f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.8
    - jaxtyping >=0.2.9
    - pytorch >=1.11
    - scipy
    - typeguard ~=2.13.3

test:
  imports:
    - linear_operator
    - linear_operator.functions
    - linear_operator.operators
    - linear_operator.test
    - linear_operator.utils
  requires:
    - pip
  commands:
    - pip check
    - python -c "import linear_operator; print(linear_operator.__version__)"

about:
  home: https://github.com/cornellius-gp/linear_operator
  summary: A LinearOperator implementation to wrap the numerical nuts and bolts of GPyTorch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/cornellius-gp/linear_operator

extra:
  recipe-maintainers:
    - AdrianSosic
    - ngam
    - thewchan
